name: Alpine build and tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '38 2 * * *'

jobs:
  alpine-build:
    runs-on: ubuntu-latest
    container: alpine:latest
    timeout-minutes: 30

    steps:
      - name: install dependencies
        run: apk add --no-cache build-base cmake linux-headers git
      - uses: actions/checkout@v6
      - name: configure
        run: mkdir build && cd build && cmake .. -DBUILDING_TESTS=1 -DCMAKE_COMPILE_WARNING_AS_ERROR=ON
      - name: build
        run: cmake --build build --config Debug
      - name: test
        run: cd build && ctest --output-on-failure
