name: Check PR title

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read

jobs:
  check_pr_title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Check PR title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: .github/check_pr_title.sh
