name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on: [pull_request]

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ZedThree/clang-tidy-review@v0.21.0
        id: review
        with:
          build_dir: build
          cmake_command: cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=on
          config_file: .clang-tidy
          clang_tidy_checks: ""

      # Uploads an artefact containing clang_fixes.json
      - uses: ZedThree/clang-tidy-review/upload@v0.21.0
        id: upload-review

      # If there are any comments, fail the check
      - if: steps.review.outputs.total_comments > 0
        run: exit 1
